version: '2'

services:
  web:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    image: realpage/asset-publisher:web
    env_file: .env
    volumes:
      - ./infrastructure/nginx:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - "80:80"