version: '2'

services:
  web:
    image: nginx
    volumes:
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
  fpm:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    image: realpage/asset-publisher:fpm
    env_file: .env
    volumes:
      - ./:/var/www/html