version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: infrastructure/fpm/Dockerfile
    image: realpage/npm-publisher:fpm
    env_file: .env
    volumes:
      - ./:/var/www/html
  web:
    image: realpage/nginx:1.9
    volumes:
      - ./infrastructure/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - fpm
    ports:
      - "80:80"